sudo: required

services:
- docker

before_install:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  fi

script:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    bash make_dockers.sh;
  fi

notifications:
  email: false
