language: go
go:
- 1.8.x

sudo: required

services:
- docker

before_install:
- if [ ${TRAVIS_TAG::6} = image- ];
  then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  fi

install:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    go get ./...;
  fi

script:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    make test;
  fi
- bash make_dockers.sh

after_success:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    curl -sL https://git.io/goreleaser | bash;
  fi

notifications:
  email: false
